// Copyright 2024-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file cel/expr/conformance/proto2/test_all_types_extensions.proto (package cel.expr.conformance.proto2, syntax proto2)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { TestAllTypes, TestAllTypes_NestedEnum } from "./test_all_types_pb.js";
import { file_cel_expr_conformance_proto2_test_all_types } from "./test_all_types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cel/expr/conformance/proto2/test_all_types_extensions.proto.
 */
export const file_cel_expr_conformance_proto2_test_all_types_extensions: GenFile = /*@__PURE__*/
  fileDesc("CjtjZWwvZXhwci9jb25mb3JtYW5jZS9wcm90bzIvdGVzdF9hbGxfdHlwZXNfZXh0ZW5zaW9ucy5wcm90bxIbY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yIrAEChxQcm90bzJFeHRlbnNpb25TY29wZWRNZXNzYWdlMkcKCWludDY0X2V4dBIpLmNlbC5leHByLmNvbmZvcm1hbmNlLnByb3RvMi5UZXN0QWxsVHlwZXMY7QcgASgDUghpbnQ2NEV4dDKQAQoZbWVzc2FnZV9zY29wZWRfbmVzdGVkX2V4dBIpLmNlbC5leHByLmNvbmZvcm1hbmNlLnByb3RvMi5UZXN0QWxsVHlwZXMY7gcgASgLMikuY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yLlRlc3RBbGxUeXBlc1IWbWVzc2FnZVNjb3BlZE5lc3RlZEV4dDKIAQoPbmVzdGVkX2VudW1fZXh0EikuY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yLlRlc3RBbGxUeXBlcxjvByABKA4yNC5jZWwuZXhwci5jb25mb3JtYW5jZS5wcm90bzIuVGVzdEFsbFR5cGVzLk5lc3RlZEVudW1SDW5lc3RlZEVudW1FeHQyqAEKJm1lc3NhZ2Vfc2NvcGVkX3JlcGVhdGVkX3Rlc3RfYWxsX3R5cGVzEikuY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yLlRlc3RBbGxUeXBlcxjwByADKAsyKS5jZWwuZXhwci5jb25mb3JtYW5jZS5wcm90bzIuVGVzdEFsbFR5cGVzUiFtZXNzYWdlU2NvcGVkUmVwZWF0ZWRUZXN0QWxsVHlwZXM6RwoJaW50MzJfZXh0EikuY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yLlRlc3RBbGxUeXBlcxjoByABKAVSCGludDMyRXh0OnQKCm5lc3RlZF9leHQSKS5jZWwuZXhwci5jb25mb3JtYW5jZS5wcm90bzIuVGVzdEFsbFR5cGVzGOkHIAEoCzIpLmNlbC5leHByLmNvbmZvcm1hbmNlLnByb3RvMi5UZXN0QWxsVHlwZXNSCW5lc3RlZEV4dDqCAQoSdGVzdF9hbGxfdHlwZXNfZXh0EikuY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yLlRlc3RBbGxUeXBlcxjqByABKAsyKS5jZWwuZXhwci5jb25mb3JtYW5jZS5wcm90bzIuVGVzdEFsbFR5cGVzUg90ZXN0QWxsVHlwZXNFeHQ6iAEKD25lc3RlZF9lbnVtX2V4dBIpLmNlbC5leHByLmNvbmZvcm1hbmNlLnByb3RvMi5UZXN0QWxsVHlwZXMY6wcgASgOMjQuY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yLlRlc3RBbGxUeXBlcy5OZXN0ZWRFbnVtUg1uZXN0ZWRFbnVtRXh0OowBChdyZXBlYXRlZF90ZXN0X2FsbF90eXBlcxIpLmNlbC5leHByLmNvbmZvcm1hbmNlLnByb3RvMi5UZXN0QWxsVHlwZXMY7AcgAygLMikuY2VsLmV4cHIuY29uZm9ybWFuY2UucHJvdG8yLlRlc3RBbGxUeXBlc1IUcmVwZWF0ZWRUZXN0QWxsVHlwZXNCXwofZGV2LmNlbC5leHByLmNvbmZvcm1hbmNlLnByb3RvMkIWVGVzdEFsbFR5cGVzRXh0ZW5zaW9uc1ABWh9jZWwuZGV2L2V4cHIvY29uZm9ybWFuY2UvcHJvdG8y+AEB", [file_cel_expr_conformance_proto2_test_all_types]);

/**
 * Message scoped extensions
 *
 * @generated from message cel.expr.conformance.proto2.Proto2ExtensionScopedMessage
 */
export type Proto2ExtensionScopedMessage = Message<"cel.expr.conformance.proto2.Proto2ExtensionScopedMessage"> & {
};

/**
 * Describes the message cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.
 * Use `create(Proto2ExtensionScopedMessageSchema)` to create a new message.
 */
export const Proto2ExtensionScopedMessageSchema: GenMessage<Proto2ExtensionScopedMessage> = /*@__PURE__*/
  messageDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 0);

/**
 * @generated from extension: optional int64 int64_ext = 1005;
 */
export const Proto2ExtensionScopedMessage_int64_ext: GenExtension<TestAllTypes, bigint> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 0, 0);

/**
 * @generated from extension: optional cel.expr.conformance.proto2.TestAllTypes message_scoped_nested_ext = 1006;
 */
export const Proto2ExtensionScopedMessage_message_scoped_nested_ext: GenExtension<TestAllTypes, TestAllTypes> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 0, 1);

/**
 * @generated from extension: optional cel.expr.conformance.proto2.TestAllTypes.NestedEnum nested_enum_ext = 1007;
 */
export const Proto2ExtensionScopedMessage_nested_enum_ext: GenExtension<TestAllTypes, TestAllTypes_NestedEnum> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 0, 2);

/**
 * @generated from extension: repeated cel.expr.conformance.proto2.TestAllTypes message_scoped_repeated_test_all_types = 1008;
 */
export const Proto2ExtensionScopedMessage_message_scoped_repeated_test_all_types: GenExtension<TestAllTypes, TestAllTypes[]> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 0, 3);

/**
 * @generated from extension: optional int32 int32_ext = 1000;
 */
export const int32_ext: GenExtension<TestAllTypes, number> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 0);

/**
 * @generated from extension: optional cel.expr.conformance.proto2.TestAllTypes nested_ext = 1001;
 */
export const nested_ext: GenExtension<TestAllTypes, TestAllTypes> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 1);

/**
 * @generated from extension: optional cel.expr.conformance.proto2.TestAllTypes test_all_types_ext = 1002;
 */
export const test_all_types_ext: GenExtension<TestAllTypes, TestAllTypes> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 2);

/**
 * @generated from extension: optional cel.expr.conformance.proto2.TestAllTypes.NestedEnum nested_enum_ext = 1003;
 */
export const nested_enum_ext: GenExtension<TestAllTypes, TestAllTypes_NestedEnum> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 3);

/**
 * @generated from extension: repeated cel.expr.conformance.proto2.TestAllTypes repeated_test_all_types = 1004;
 */
export const repeated_test_all_types: GenExtension<TestAllTypes, TestAllTypes[]> = /*@__PURE__*/
  extDesc(file_cel_expr_conformance_proto2_test_all_types_extensions, 4);

