// Copyright 2024-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file cel/expr/explain.proto (package cel.expr, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Value } from "./value_pb.js";
import { file_cel_expr_value } from "./value_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cel/expr/explain.proto.
 */
export const file_cel_expr_explain: GenFile = /*@__PURE__*/
  fileDesc("ChZjZWwvZXhwci9leHBsYWluLnByb3RvEghjZWwuZXhwciKLAQoHRXhwbGFpbhIfCgZ2YWx1ZXMYASADKAsyDy5jZWwuZXhwci5WYWx1ZRIuCgpleHByX3N0ZXBzGAIgAygLMhouY2VsLmV4cHIuRXhwbGFpbi5FeHByU3RlcBorCghFeHByU3RlcBIKCgJpZBgBIAEoAxITCgt2YWx1ZV9pbmRleBgCIAEoBToCGAFCLwoMZGV2LmNlbC5leHByQgxFeHBsYWluUHJvdG9QAVoMY2VsLmRldi9leHBy+AEBYgZwcm90bzM", [file_cel_expr_value]);

/**
 * Values of intermediate expressions produced when evaluating expression.
 *
 * @generated from message cel.expr.Explain
 * @deprecated
 */
export type Explain = Message<"cel.expr.Explain"> & {
  /**
   * All of the observed values.
   *
   * The field value_index is an index in the values list.
   * Separating values from steps is needed to remove redundant values.
   *
   * @generated from field: repeated cel.expr.Value values = 1;
   */
  values: Value[];

  /**
   * List of steps.
   *
   * Repeated evaluations of the same expression generate new ExprStep
   * instances. The order of such ExprStep instances matches the order of
   * elements returned by Comprehension.iter_range.
   *
   * @generated from field: repeated cel.expr.Explain.ExprStep expr_steps = 2;
   */
  exprSteps: Explain_ExprStep[];
};

/**
 * Describes the message cel.expr.Explain.
 * Use `create(ExplainSchema)` to create a new message.
 * @deprecated
 */
export const ExplainSchema: GenMessage<Explain> = /*@__PURE__*/
  messageDesc(file_cel_expr_explain, 0);

/**
 * ID and value index of one step.
 *
 * @generated from message cel.expr.Explain.ExprStep
 * @deprecated
 */
export type Explain_ExprStep = Message<"cel.expr.Explain.ExprStep"> & {
  /**
   * ID of corresponding Expr node.
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * Index of the value in the values list.
   *
   * @generated from field: int32 value_index = 2;
   */
  valueIndex: number;
};

/**
 * Describes the message cel.expr.Explain.ExprStep.
 * Use `create(Explain_ExprStepSchema)` to create a new message.
 * @deprecated
 */
export const Explain_ExprStepSchema: GenMessage<Explain_ExprStep> = /*@__PURE__*/
  messageDesc(file_cel_expr_explain, 0, 0);

