// Copyright 2024-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file cel/expr/value.proto (package cel.expr, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Any, NullValue } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cel/expr/value.proto.
 */
export const file_cel_expr_value: GenFile = /*@__PURE__*/
  fileDesc("ChRjZWwvZXhwci92YWx1ZS5wcm90bxIIY2VsLmV4cHIikAMKBVZhbHVlEjAKCm51bGxfdmFsdWUYASABKA4yGi5nb29nbGUucHJvdG9idWYuTnVsbFZhbHVlSAASFAoKYm9vbF92YWx1ZRgCIAEoCEgAEhUKC2ludDY0X3ZhbHVlGAMgASgDSAASFgoMdWludDY0X3ZhbHVlGAQgASgESAASFgoMZG91YmxlX3ZhbHVlGAUgASgBSAASFgoMc3RyaW5nX3ZhbHVlGAYgASgJSAASFQoLYnl0ZXNfdmFsdWUYByABKAxIABIpCgplbnVtX3ZhbHVlGAkgASgLMhMuY2VsLmV4cHIuRW51bVZhbHVlSAASLAoMb2JqZWN0X3ZhbHVlGAogASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUgAEicKCW1hcF92YWx1ZRgLIAEoCzISLmNlbC5leHByLk1hcFZhbHVlSAASKQoKbGlzdF92YWx1ZRgMIAEoCzITLmNlbC5leHByLkxpc3RWYWx1ZUgAEhQKCnR5cGVfdmFsdWUYDyABKAlIAEIGCgRraW5kIigKCUVudW1WYWx1ZRIMCgR0eXBlGAEgASgJEg0KBXZhbHVlGAIgASgFIiwKCUxpc3RWYWx1ZRIfCgZ2YWx1ZXMYASADKAsyDy5jZWwuZXhwci5WYWx1ZSJ8CghNYXBWYWx1ZRIpCgdlbnRyaWVzGAEgAygLMhguY2VsLmV4cHIuTWFwVmFsdWUuRW50cnkaRQoFRW50cnkSHAoDa2V5GAEgASgLMg8uY2VsLmV4cHIuVmFsdWUSHgoFdmFsdWUYAiABKAsyDy5jZWwuZXhwci5WYWx1ZUItCgxkZXYuY2VsLmV4cHJCClZhbHVlUHJvdG9QAVoMY2VsLmRldi9leHBy+AEBYgZwcm90bzM", [file_google_protobuf_any, file_google_protobuf_struct]);

/**
 * Represents a CEL value.
 *
 * This is similar to `google.protobuf.Value`, but can represent CEL's full
 * range of values.
 *
 * @generated from message cel.expr.Value
 */
export type Value = Message<"cel.expr.Value"> & {
  /**
   * Required. The valid kinds of values.
   *
   * @generated from oneof cel.expr.Value.kind
   */
  kind: {
    /**
     * Null value.
     *
     * @generated from field: google.protobuf.NullValue null_value = 1;
     */
    value: NullValue;
    case: "nullValue";
  } | {
    /**
     * Boolean value.
     *
     * @generated from field: bool bool_value = 2;
     */
    value: boolean;
    case: "boolValue";
  } | {
    /**
     * Signed integer value.
     *
     * @generated from field: int64 int64_value = 3;
     */
    value: bigint;
    case: "int64Value";
  } | {
    /**
     * Unsigned integer value.
     *
     * @generated from field: uint64 uint64_value = 4;
     */
    value: bigint;
    case: "uint64Value";
  } | {
    /**
     * Floating point value.
     *
     * @generated from field: double double_value = 5;
     */
    value: number;
    case: "doubleValue";
  } | {
    /**
     * UTF-8 string value.
     *
     * @generated from field: string string_value = 6;
     */
    value: string;
    case: "stringValue";
  } | {
    /**
     * Byte string value.
     *
     * @generated from field: bytes bytes_value = 7;
     */
    value: Uint8Array;
    case: "bytesValue";
  } | {
    /**
     * An enum value.
     *
     * @generated from field: cel.expr.EnumValue enum_value = 9;
     */
    value: EnumValue;
    case: "enumValue";
  } | {
    /**
     * The proto message backing an object value.
     *
     * @generated from field: google.protobuf.Any object_value = 10;
     */
    value: Any;
    case: "objectValue";
  } | {
    /**
     * Map value.
     *
     * @generated from field: cel.expr.MapValue map_value = 11;
     */
    value: MapValue;
    case: "mapValue";
  } | {
    /**
     * List value.
     *
     * @generated from field: cel.expr.ListValue list_value = 12;
     */
    value: ListValue;
    case: "listValue";
  } | {
    /**
     * Type value.
     *
     * @generated from field: string type_value = 15;
     */
    value: string;
    case: "typeValue";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message cel.expr.Value.
 * Use `create(ValueSchema)` to create a new message.
 */
export const ValueSchema: GenMessage<Value> = /*@__PURE__*/
  messageDesc(file_cel_expr_value, 0);

/**
 * An enum value.
 *
 * @generated from message cel.expr.EnumValue
 */
export type EnumValue = Message<"cel.expr.EnumValue"> & {
  /**
   * The fully qualified name of the enum type.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * The value of the enum.
   *
   * @generated from field: int32 value = 2;
   */
  value: number;
};

/**
 * Describes the message cel.expr.EnumValue.
 * Use `create(EnumValueSchema)` to create a new message.
 */
export const EnumValueSchema: GenMessage<EnumValue> = /*@__PURE__*/
  messageDesc(file_cel_expr_value, 1);

/**
 * A list.
 *
 * Wrapped in a message so 'not set' and empty can be differentiated, which is
 * required for use in a 'oneof'.
 *
 * @generated from message cel.expr.ListValue
 */
export type ListValue = Message<"cel.expr.ListValue"> & {
  /**
   * The ordered values in the list.
   *
   * @generated from field: repeated cel.expr.Value values = 1;
   */
  values: Value[];
};

/**
 * Describes the message cel.expr.ListValue.
 * Use `create(ListValueSchema)` to create a new message.
 */
export const ListValueSchema: GenMessage<ListValue> = /*@__PURE__*/
  messageDesc(file_cel_expr_value, 2);

/**
 * A map.
 *
 * Wrapped in a message so 'not set' and empty can be differentiated, which is
 * required for use in a 'oneof'.
 *
 * @generated from message cel.expr.MapValue
 */
export type MapValue = Message<"cel.expr.MapValue"> & {
  /**
   * The set of map entries.
   *
   * CEL has fewer restrictions on keys, so a protobuf map representation
   * cannot be used.
   *
   * @generated from field: repeated cel.expr.MapValue.Entry entries = 1;
   */
  entries: MapValue_Entry[];
};

/**
 * Describes the message cel.expr.MapValue.
 * Use `create(MapValueSchema)` to create a new message.
 */
export const MapValueSchema: GenMessage<MapValue> = /*@__PURE__*/
  messageDesc(file_cel_expr_value, 3);

/**
 * @generated from message cel.expr.MapValue.Entry
 */
export type MapValue_Entry = Message<"cel.expr.MapValue.Entry"> & {
  /**
   * The key.
   *
   * Must be unique with in the map.
   * Currently only boolean, int, uint, and string values can be keys.
   *
   * @generated from field: cel.expr.Value key = 1;
   */
  key?: Value;

  /**
   * The value.
   *
   * @generated from field: cel.expr.Value value = 2;
   */
  value?: Value;
};

/**
 * Describes the message cel.expr.MapValue.Entry.
 * Use `create(MapValue_EntrySchema)` to create a new message.
 */
export const MapValue_EntrySchema: GenMessage<MapValue_Entry> = /*@__PURE__*/
  messageDesc(file_cel_expr_value, 3, 0);

